In [6]:
import os
from pathlib import Path

# CHANGE THIS if your folder name is slightly different
PROJECT_ROOT = Path(r"d:\github\quant-projects\ATR_Beta_Hedged_Breakout")

os.chdir(PROJECT_ROOT)

samples = [p.name for p in Path("data/samples").glob("*")]
print("Sample files:", samples)
from src.data_loader import load_mt5_m1_csv
print("import OK")

Sample files: ['NDX100_M1_SERVER_2024-01-03_2024-01-31.csv', 'SPX500_M1_SERVER_2024-01-03_2024-01-31.csv']
import OK

In [7]:
ndx = load_mt5_m1_csv(
    "data/samples/NDX100_M1_SERVER_2024-01-03_2024-01-31.csv"
)

ndx.head()

,timestamp,open,high,low,close,tick_volume,spread
0,2024-01-03 01:00:00,16547.95,16547.95,16547.95,16547.95,1,140
1,2024-01-03 01:01:00,16547.71,16547.71,16547.71,16547.71,1,140
2,2024-01-03 01:02:00,16545.61,16545.61,16545.61,16545.61,1,140
3,2024-01-03 01:03:00,16545.61,16545.61,16545.61,16545.61,1,140
4,2024-01-03 01:04:00,16545.61,16545.61,16545.61,16545.61,1,140

In [ ]:
spx = load_mt5_m1_csv(
    "data/samples/SPX500_M1_SERVER_2024-01-03_2024-01-31.csv"
)

spx.head()

            timestamp     open     high      low    close  tick_volume  spread
0 2024-01-03 01:00:00  4745.61  4745.61  4745.61  4745.61            1      45
1 2024-01-03 01:01:00  4745.12  4745.12  4745.12  4745.12            1      45
2 2024-01-03 01:02:00  4744.75  4744.75  4744.75  4744.75            1      45
3 2024-01-03 01:03:00  4744.75  4744.75  4744.75  4744.75            1      45
4 2024-01-03 01:04:00  4745.00  4745.00  4745.00  4745.00            1      45